### ISSUE TITLE
Mujina-idp faild to start and other java app

### ISSUE THREAD

**Issue by mkoyan44** [OpenConext/OpenConext-deploy#132]
Hi guys,
Pleass support.Mujina idp and sp and other java apps failed to start.

systemctl status mujina-idp
● mujina-idp.service - mujina-idp
Loaded: loaded (/etc/systemd/system/mujina-idp.service; enabled; vendor preset: disabled)
Active: failed (Result: exit-code) since Thu 2017-05-11 13:26:33 CEST; 282ms ago
Process: 4149 ExecStart=/usr/lib/jvm/java-1.8.0/bin/java -Xms128m -Xmx128m -Djava.security.egd=file:///dev/urandom -jar mujina-idp-current.jar (code=exited, status=1/FAILURE)
Main PID: 4149 (code=exited, status=1/FAILURE)

May 11 13:26:26 welcome.openconext.org java[4149]: .   ____          _            __ _ _
May 11 13:26:26 welcome.openconext.org java[4149]: /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
May 11 13:26:26 welcome.openconext.org java[4149]: ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
May 11 13:26:26 welcome.openconext.org java[4149]: \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
May 11 13:26:26 welcome.openconext.org java[4149]: '  |____| .__|_| |_|_| |_\__, | / / / /
May 11 13:26:26 welcome.openconext.org java[4149]: =========|_|==============|___/=/_/_/_/
May 11 13:26:26 welcome.openconext.org java[4149]: :: Spring Boot ::        (v1.5.2.RELEASE)
May 11 13:26:33 welcome.openconext.org systemd[1]: mujina-idp.service: main process exited, code=exited, status=...LURE
May 11 13:26:33 welcome.openconext.org systemd[1]: Unit mujina-idp.service entered failed state.
May 11 13:26:33 welcome.openconext.org systemd[1]: mujina-idp.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

Please also see the log service.

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-05-11 13:31:40,926 ERROR [main] o.springframework.boot.SpringApplication:815 - Application startup failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'idpConfiguration' defined in URL [jar:file:/opt/mujina-idp/mujina-idp-5.0.3.jar!/BOOT-INF/classes!/mujina/api/IdpConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'keyManager' defined in class path resource [mujina/idp/WebSecurityConfigurer.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.saml.key.JKSKeyManager]: Factory method 'keyManager' threw exception; nested exception is java.lang.IllegalArgumentException: Illegal base64 character 5f
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
	at mujina.MujinaIdpApplication.main(MujinaIdpApplication.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'keyManager' defined in class path resource [mujina/idp/WebSecurityConfigurer.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.saml.key.JKSKeyManager]: Factory method 'keyManager' threw exception; nested exception is java.lang.IllegalArgumentException: Illegal base64 character 5f
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 27 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.saml.key.JKSKeyManager]: Factory method 'keyManager' threw exception; nested exception is java.lang.IllegalArgumentException: Illegal base64 character 5f
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 40 common frames omitted
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 5f
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at mujina.saml.KeyStoreLocator.addPrivateKey(KeyStoreLocator.java:47)
	at mujina.idp.WebSecurityConfigurer.keyManager(WebSecurityConfigurer.java:101)
	at mujina.idp.WebSecurityConfigurer$$EnhancerBySpringCGLIB$$8675f554.CGLIB$keyManager$1(<generated>)
	at mujina.idp.WebSecurityConfigurer$$EnhancerBySpringCGLIB$$8675f554$$FastClassBySpringCGLIB$$5609d8f0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at mujina.idp.WebSecurityConfigurer$$EnhancerBySpringCGLIB$$8675f554.keyManager(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)

**Comment by mkoyan44** [comment]
Dear Comunity,

I overcome the issue by adding private in secret/<env>.yml in mujina_idp.key and mujina.sp.key file.
